
async function main() {

}

main().then(r => console.log('done')).catch(e => console.error(e));